### ISSUE TITLE
feat: add Android implementation

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-background-task#13]
**Is your feature request related to a problem? Please describe:**

There is currently no ready implementation on Android.

**Describe the solution you'd like:**

Add an implementation for Android.

**Comment by notflip** [comment]
So what would happen if I were to run the sample code on Android?

**Comment by notflip** [comment]
All right, thanks for the heads up!

**Comment by robingenz** [comment]
A short notice: There is now an [Android Foreground Service plugin](https://github.com/capawesome-team/capacitor-android-foreground-service) that allows you to run Capacitor apps (Android only, iOS does not support this without further conditions) permanently in the background (unless they are force closed). 
This plugin can be combined very well with other plugins like this or https://github.com/transistorsoft/capacitor-background-fetch.

**Comment by robingenz** [comment]
For now, I'm closing this issue as not planned.
