### ISSUE TITLE
Add to capacitor community plugins

### ISSUE THREAD

**Issue by pete-mcwilliams** [capawesome-team/capacitor-background-task#14]
**Describe the solution you'd like:**
Plugin to be added to the capacitor community plugins.  Adding feature request to cross reference to the plugin propsal.

**Additional context:**
https://github.com/capacitor-community/proposals/issues/108

**Comment by robingenz** [comment]
Hi @pete-mcwilliams,
thank you for your request.
This plugin is now maintained by the Capawesome Organization.
We do not plan to move it to the Capacitor Community Organization.
