### ISSUE TITLE
bug: Called Hundreds of Times Inside useEffect()

### ISSUE THREAD

**Issue by AlvinStefanus** [capawesome-team/capacitor-background-task#22]
**Plugin version:**
1.0.1

**Platform(s):**
IOS and Android

**Current behavior:**
Keep calling the parent function hundreds of times

**Expected behavior:**
Should run once

**Steps to reproduce:**

I am placing the `const taskId = await BackgroundTask.beforeExit(async () => {` inside `useEffect()`.
I am expecting that the `http request` and `updateDB()` to be ran background. This is to prevent sudden termination from the user after sending `http request` and before updating the database. It can cause problem because the data need to be synced. If the user terminate the app after sending `http request` and not updating the database after that, the next time the user launch the application, the application will try to send the `http request` to the server, this cause duplicate data being sent.

However this code behaves incredibly weird, the `const syncingOut = async () => {` is called hundreds of times causing hundreds of `http request` and `updateDB()` being called simultaneously. It should be called once.

**Related code:**

```
export const useSynchronizer = () => {

  .....
  .....

  useEffect(() => {
    if (syncOut.length > 0) syncingOut()
  }, [syncOut, isSyncingOut]);

  const syncingOut = async () => {
    if (!isSyncingOut) {
      dispatch(setIsSyncingOut(true));
      if (syncOut.length > 0) {
        let job = syncOut[0];
        switch (job.type) {
          case 'POST': {
              const taskId = await BackgroundTask.beforeExit(async () => {
                let r = await Http.post(nav, job.url, job.params, job.model, job.syncToken);
                await updateDB(r, job);
                BackgroundTask.finish({ taskId });
              });
              break;
          }
          case 'PUT': {
              const taskId = await BackgroundTask.beforeExit(async () => {
                let r = await Http.put(nav, job.url, job.params, job.model, job.syncToken);
                await updateDB(r, job);
                BackgroundTask.finish({ taskId });
              });
              break;
          }
          case 'DELETE': {
            if (!isWeb()) {
              const taskId = await BackgroundTask.beforeExit(async () => {
                let r = await Http.delete(nav, job.url, job.params, job.syncToken);
                await updateDB(r, job);
                BackgroundTask.finish({ taskId });
              });
              break;
          }
        }
        dispatch(setIsSyncingOut(false));
      } else {
        dispatch(setIsSyncingOut(false));
      }
    }
  }
```

**Other information:**
None

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.4.0
  @capacitor/core: 3.5.1
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0

[success] iOS looking great! 👌
[success] Android looking great! 👌```

**Comment by AlvinStefanus** [comment]
There is no problem with my `useEffect()` if I remove the `const taskId = await BackgroundTask.beforeExit(async () => {` wrapping from the code, it works just fine. It is called just once.

**Comment by AlvinStefanus** [comment]
@robingenz sorry for the lack of example. I had found the solution for my problem.

```
useEffect(() => {
    if (syncOut.length > 0) syncingOut()
  }, [syncOut, isSyncingOut]);

  //SYNC OUT

  const syncingOut = async () => {
    if(!isWeb()) {
      const taskId = await BackgroundTask.beforeExit(async () => {
        await syncingOutFunc();
        BackgroundTask.finish({ taskId });
      })
    } else {
      await syncingOutFunc();
    }
  }

  const syncingOutFunc = async () => {
    if (!isSyncingOut) {
      dispatch(setIsSyncingOut(true));
      if (syncOut.length > 0) {
        let job = syncOut[0];
        switch (job.type) {
          case 'POST': {
            let r = await Http.post(nav, job.url, job.params, job.model, job.syncToken);
            await updateDB(r, job);
            break;
          }
          case 'PUT': {
            let r = await Http.put(nav, job.url, job.params, job.model, job.syncToken);
            await updateDB(r, job);
            break;
          }
          case 'DELETE': {
            let r = await Http.delete(nav, job.url, job.params, job.syncToken);
            await updateDB(r, job);
            break;
          }
        }
        dispatch(setIsSyncingOut(false));
      } else {
        dispatch(setIsSyncingOut(false));
      }
    }
  }
```

What I did was to move the:

`const taskId = await BackgroundTask.beforeExit(async () => {`

to the top and warp all of the syncing logics. Before this I was calling the background task on each switch cases. Now I wrap all my switch cases inside the background task.

I am still unsure why this work tho. Maybe you can get a clue and explain why this work.

Thanks

**Comment by AlvinStefanus** [comment]
Maybe because the background task saves all the states above it? Maybe it saves all function states above it, that is why it is called multiple times, almost infinitely, but I am not sure.

**Comment by robingenz** [comment]
I am glad that it works now. I am closing the issue.
As I said before, unfortunately I don't have any experience with React.
Feel free to check out the [demo app](https://github.com/robingenz/capacitor-plugin-demo) to get an example of how it works.
