### ISSUE TITLE
feat: Capacitor V4 support

### ISSUE THREAD

**Issue by Chewbye** [capawesome-team/capacitor-background-task#23]
Hello,

Following Capacitor v4 realease.

Do you plan to support this version?

Thanks!

**Comment by robingenz** [comment]
Yes, I will release an update over the next week.

**Comment by robingenz** [comment]
You can give ot a try: 

```
npm i @robingenz/capacitor-background-task@1.0.1-dev.5e2ac0e.1659272460
```
